language: node_js
node_js:
  - '0.10.32'
before_script:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'npm install -g bower karma-cli grunt-cli jshint'
  - 'grunt auto_install' # install npm packages
